version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud_storage
    depends_on:
      - db
    volumes:
      - file-storage:/app/storage

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=cloud_storage
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  file-storage: